### ISSUE TITLE
Windows 10 and open-saas error

### ISSUE THREAD

**Issue by Traveltainer007** [wasp-lang/open-saas#100]
D:\open-saas>curl -sSL https://get.wasp-lang.dev/installer.sh | sh
Sorry, this installer does not support your operating system: MSYS_NT-10.0-19045.

D:\open-saas>

Based on the search results, it appears that the Open SaaS template is not directly compatible with Windows 10 using the MSYS environment. The installer script provided is designed to install the Wasp framework on Linux and macOS systems, but not on Windows 10 with the MSYS environment.

The error message "Sorry, this installer does not support your operating system: MSYS_NT-10.0-19045" indicates that the Wasp installer is not able to handle the MSYS environment on Windows 10.[1][2]

To install and run the Open SaaS template on Windows 10, you would need to find an alternative approach, such as using a Windows Subsystem for Linux (WSL) environment or exploring other options for running the Wasp framework on Windows. The documentation for the Open SaaS template may provide more guidance on supported platforms and installation methods.

Citations:
[1] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/308339/8ad0ab97-01de-4b15-8c41-0fee6b55869c/paste.txt
[2] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/308339/16490f07-f139-4440-93cf-fa4a1dd1a650/paste-2.txt
[3] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/308339/5f1c02d4-c9b9-4b94-b282-c6228e839c47/paste-3.txt

**Comment by Martinsos** [comment]
Yup this is correct, you need to use WSL on Windows! Not sure why did you open an issue though, but I hope you figured it out!
