### ISSUE TITLE
Can we integrate other payment gateways

### ISSUE THREAD

**Issue by Tdnshah** [wasp-lang/open-saas#103]
I would like to know if it is possible to integrate other local payment gateways than stripe ?

**Comment by infomiho** [comment]
There were requests on Discord for Paypal and Paddle.me

Thread: https://ptb.discord.com/channels/686873244791210014/1232775770263392368/1233880861200355359

**Comment by Tdnshah** [comment]
So, I was looking from Indian markets prespective to payment gateways like Razorpay, Instamojo, Cashfree etc.. I would love to take this if we have a documentation on how to do this

**Comment by ytad** [comment]
@infomiho I'm sure you mean Paddle.com. After researching this topic, it seems like Paddle.com is one of the established solutions. I have read many links, especially I like this discussion https://www.reddit.com/r/SaaS/comments/13noyxv/paddle_vs_lemon_squeezy_experiences
