### ISSUE TITLE
unable to getting started

### ISSUE THREAD

**Issue by JOduMonT** [wasp-lang/open-saas#114]
I want to follow your [getting started](https://docs.opensaas.sh/start/getting-started/) but it start badly

curl -sSL https://get.wasp-lang.dev/installer.sh | sh
curl: (77) error setting certificate file: /etc/ssl/certs/ca-certificates.crt

even when I download manually the script
the error remains

**Comment by Martinsos** [comment]
I am closing the issue as I am quite confident it is not issue with Wasp, but we can continue chatting here in the closed issue.
