### ISSUE TITLE
When port 3000 is not available, and the db is already running, intermittent issues occur when running 

### ISSUE THREAD

**Issue by Reikon95** [wasp-lang/open-saas#116]
I found this by accident today - if you're running the db, but already running something on port 3000 locally, you'll get random "cannot get" issues when loading certain pages on 3001 (or whatever it defaults to) - not sure if it makes a difference, but only when they were behind auth

Not a breaking issue, but could be a good idea to add a warning to the start script.

**Comment by Martinsos** [comment]
So server listens on port 3001 and client on port 3000 -> so if you already have sometihng running on 3000, then client wont run and there will be issues!

You are right, would be good if we have a better handling for this, but we didn't get to it yet. We do have an issue that aims to solve this in a way: https://github.com/wasp-lang/wasp/issues/730 .

Thanks for reporting this, I will be closign this one in favor or the issue I linked, but if you think there is more tot his let me know and we can reopen / add that info!
