### ISSUE TITLE
Logout button missing padding on mobile devices

### ISSUE THREAD

**Issue by LouisDeconinck** [wasp-lang/open-saas#118]
There seems to be some padding missing on the logout button on the account page on smaller devices.
![image](https://github.com/wasp-lang/open-saas/assets/27673665/bb454125-08fc-466a-b7f9-1f57bc29aa8d)

**Comment by Martinsos** [comment]
Oh nice catch! If you fixed it on our side, would you be interested in making a PR with the styling changes?

**Comment by Lathiya50** [comment]
Hi @Martinsos 
I've fixed the issue. Please review the changes in PR #243.

Thank you!
