### ISSUE TITLE
checkStripePortalLinkExists throws an error

### ISSUE THREAD

**Issue by LouisDeconinck** [wasp-lang/open-saas#119]
The documentation (https://docs.opensaas.sh/guides/stripe-integration/) says to add this code to the src/shared/constants.ts file:
```javacript
const customerPortalTestUrl = 'https//billing.stripe.com/p/login/test_...'
const customerPortalProdUrl = undefined

export const STRIPE_CUSTOMER_PORTAL_LINK = isDev ? customerPortalTestUrl : customerPortalProdUrl;

checkStripePortalLinkExists(STRIPE_CUSTOMER_PORTAL_LINK); // throws an error if the link is not set in production
```

isDev and checkStripePortalLinkExists are not defined and throw an error.

@vincanger mentioned in the Discord:
_"Ah this looks like a mistake. We removed this check recently I believe but forgot to remove it from the docs
So you can just ignore that portion of the docs. You should see the customer portal link in .env.client instead"_

**Comment by vincanger** [comment]
@LouisDeconinck this has been fixed in the most recent update --> https://docs.opensaas.sh/guides/stripe-integration/#get-your-customer-portal-link

thanks for the heads up :)
