### ISSUE TITLE
please add simple to do app with picture upload

### ISSUE THREAD

**Issue by musfandi** [wasp-lang/open-saas#12]
please add simple to do app with picture upload to open-saas

**Comment by Martinsos** [comment]
Hey @musfandi , would you mind elaborating a bit more?

How would you imagine image upload would fit into this example app -> for uploading profile photo for a user? Or in general for uploading photos?

Are you interested in a specific way to upload images -> via AWS (S3), Azure (Buckets), something else?

**Comment by musfandi** [comment]
yes, user profile is better   
Uploadthing is more simple to handle

**Comment by vincanger** [comment]
closing this issue as this one is more detailed https://github.com/wasp-lang/open-saas/issues/25
