### ISSUE TITLE
add Cookies Banner to main template

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#123]
- [x] add cookie consent banner component w/ accept or reject all cookies
- [x] add e2e tests
- [ ] update docs with updated analytics integration & cookie consent info (how it works etc)

**Comment by LouisDeconinck** [comment]
Would be nice to implement a flag to easily toggle this on or off.

**Comment by vincanger** [comment]
PR https://github.com/wasp-lang/open-saas/pull/125

**Comment by vincanger** [comment]
taken care of in https://github.com/wasp-lang/open-saas/pull/163
