### ISSUE TITLE
Does it support server-side rendering, which can be more conducive to SEO

### ISSUE THREAD

**Issue by apple1413** [wasp-lang/open-saas#128]
Hellow,Does it support server-side rendering(SSR), which can be more conducive to SEO?

**Comment by Martinsos** [comment]
Not yet unfortunately, but it is one of the next things on our roadmap!

Check out here for more info: https://github.com/wasp-lang/wasp/issues/911 .

Duplicate of https://github.com/wasp-lang/wasp/issues/911 .
