### ISSUE TITLE
I'm struggling to get SENDGRID_API_KEY working in production.

### ISSUE THREAD

**Issue by connorholm** [wasp-lang/open-saas#129]
After testing locally, SendGrid is able to send emails. However, after deploying to Fly.io, it doesn't seem to recognize my API key. Has anyone experienced something similar? I followed the wasp documentation for adding env vars and that didn't work. Any help would be appreciated, thanks!

![Screenshot from 2024-05-20 01-12-58](https://github.com/wasp-lang/open-saas/assets/50306883/0e0f77b8-ec03-49cf-8c7c-6244a60c36ce)

**Comment by Martinsos** [comment]
@connorholm what was the solution at the end?
