### ISSUE TITLE
Improve the deployment docs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#139]
User here went through quite some trouble to deploy open-saas app because he wasn't aware of the env vars they need to set up on the Fly.io : https://discord.com/channels/686873244791210014/1241745021955473548/1241745021955473548 .

Open-saas docs for deployment ( https://docs.opensaas.sh/guides/deploying/ ) are nice, they give you a couple of commands to do initial deployment and then point you to Wasp docs for deployment to learn more. Problem is, it seems from that like stuff should work even without consulting Wasp docs, as if Wasp docs are here to learn advanced stuff. But actually, just commands listed in the open-saas docs are not enough, since there might be server env vars you were supposed to set and you didn't. So open-saas docs are in a tricky state where they give you just enough info to think you know how to do it, but you are really missing information.

We can either expand open-saas docs with the missing information, or we can make it very clear that they must look into Wasp docs in order to actually successfully deploy. I think I am more for the second option. I imagine open-saas docs could give a quick high-level overview, point out a couple of things that are specific for open-saas as special "watch out for this" (like that stripe client env var) and then tell you to follow the Wasp docs to do actual deployment. This will require a bit of care to get right, but I think we can do it.

**Comment by vincanger** [comment]
ok @Martinsos i agree, so I added some extra info on ENV VARS and made explicit mentions that they should refer to the Wasp docs for deployment instructions -- 231bdee62d9199a25f17e3356aeb39da4c746a62

**Comment by Martinsos** [comment]
@vincanger can you pls revert that commit and make a PR out of it? It will be easier to review!
