### ISSUE TITLE
Prefix HOBBY_SUBSCRIPTION_PRICE_ID, PRO_SUBSCRIPTION_PRICE_ID and CREDITS_PRICE_ID env vars with STRIPE_ ?

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#145]
These are in .env.server, they are next to STRIPE_ env vars, but are not prefixed with STRIPE_. Why is that so? Are these not Stripe specific? Because of `id` part, it sounds to me like that are specific for Stripe, that `id` is id on Stripe.

If they are not specific for Stripe then ok, but if they are, we should prefix them also right?

**Comment by rugs07** [comment]
I am also getting errors here about which ID to put here? Also onclick my page isnt redirecting to stripe payment page

**Comment by vincanger** [comment]
Hi @rugs07 have you setup stripe and the customer portal link, as explained here https://docs.opensaas.sh/guides/stripe-integration/#get-your-customer-portal-link?

**Comment by vincanger** [comment]
yeah these are specific to Stripe and should be prefixed with `STRIPE_` @martinsos

**Comment by rugs07** [comment]
> Hi @rugs07 have you setup stripe as explained here https://docs.opensaas.sh/guides/stripe-integration ?
> 
> If so, can you share the console log statements coming from the server?

Sure vincanger,The console log statements are as below
Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:3001/operations/stripe-payment
index.tsx:86  Stripe Tax has not been activated on your account. Please visit https://stripe.com/docs/tax/set-up to get started.
Also I have setup the product in my stripe and have also followed the steps given on docs, but I am unable to find what to write here, export enum TierIds {
  HOBBY = 'hobby-tier',
  PRO = 'pro-tier',
  CREDITS = 'credits',
}
from my stripe product file, I have price_ID, Product_ID and product_name, I have tried all it isnt working and I have also checked my keys all are correct

**Comment by vincanger** [comment]
@rugs07 the error is telling you that stripe tax is not activated on your account. I think for some countries this is necessary or you can deactivate it in the `stripeUtils.ts` like this:
```ts
    return await stripe.checkout.sessions.create({
      line_items: [
        {
          price: priceId,
          quantity: 1,
        },
      ],
      mode: mode,
      success_url: `${DOMAIN}/checkout?success=true`,
      cancel_url: `${DOMAIN}/checkout?canceled=true`,
      automatic_tax: { enabled: false }, // changed to FALSE
      customer_update: {
        address: 'auto',
      },
      customer: customerId,
    });
    ```

**Comment by rugs07** [comment]
> @rugs07 the error is telling you that stripe tax is not activated on your account. I think for some countries this is necessary or you can deactivate it in the `stripeUtils.ts` like this:
> 
> ```ts
>     return await stripe.checkout.sessions.create({
>       line_items: [
>         {
>           price: priceId,
>           quantity: 1,
>         },
>       ],
>       mode: mode,
>       success_url: `${DOMAIN}/checkout?success=true`,
>       cancel_url: `${DOMAIN}/checkout?canceled=true`,
>       automatic_tax: { enabled: false }, // changed to FALSE
>       customer_update: {
>         address: 'auto',
>       },
>       customer: customerId,
>     });
>     ```
> ```

Also what about this part?
here, export enum TierIds {
HOBBY = 'hobby-tier',
PRO = 'pro-tier',
CREDITS = 'credits',
}

**Comment by Martinsos** [comment]
@rugs07 it might be useful if you go to our Discord Server and ask this question there in #questions, it is a better place for helping with using OpenSaas, and other community members are more likely to help, while here it is more about technical aspects of open saas itself.

https://discord.gg/rzdnErX

**Comment by vincanger** [comment]
PR --> https://github.com/wasp-lang/open-saas/pull/183
