### ISSUE TITLE
Support lemonsqueezy?

### ISSUE THREAD

**Issue by shengxinjing** [wasp-lang/open-saas#15]
Can it support lemonsqueezy’s payment system?

**Comment by vincanger** [comment]
You can definitely use lemonsqueezy instead of Stripe, but you'll have to integrate it yourself while using the Stripe integration as an example.

Adding lemonsqueezy to OpenSaaS would be a great feature. Would you be interested in creating a PR for it @shengxinjing ?

**Comment by vincanger** [comment]
hi @shengxinjing,

I'm closing this issue as I've added one here outlining what we'd need to do to add Lemon Squeezy support https://github.com/wasp-lang/open-saas/issues/16#issue-2072538852

feel free to assign yourself if this is something you'd like to take on :)
