### ISSUE TITLE
No stripe webhook trigger + cumulative subscription

### ISSUE THREAD

**Issue by Phobie53** [wasp-lang/open-saas#156]
First of all, thank you for this amazing project!

I have an issue regarding the integration of Stripe for the subscriptions of my SaaS. I have connected everything correctly and I am using the Stripe CLI properly to test locally, as I can see the logs.

However, no WebHook is being called in my project. I can see the logs in the Stripe CLI. I can see the purchase actions in my Stripe Dashboard. But despite having added logs in ./server/webhooks/stripe.ts as well as in the stripePayment function in ./server/actions.ts.

In the screenshot, you can see the logs from my Stripe CLI as well as those from my server. The client is recognized, but despite the payments, no function is being called.

Additionally, I'm not sure if this is the case, but it seems that a user might be able to accumulate subscriptions (which is not logical).

![image](https://github.com/wasp-lang/open-saas/assets/6780510/b8927923-62d0-4f20-bb9c-ea5dfef92382)

For example in my stripe.ts I got logs like this : 
```
if (event.type === 'customer.subscription.updated') {
      console.log('Subscription updated');
      ...
}
```

**Comment by vincanger** [comment]
Hi @Phobie53 

On which port is your server running? By default it should be 3001, but maybe just double check to be sure.

Then make sure you ran 

```sh
stripe listen --forward-to localhost:3001/stripe-webhook
```

**Comment by Phobie53** [comment]
Sorry, when you wrote this command, I double-checked what I was doing and realized I was running Stripe via Docker. After installing Stripe directly, it works better.
