### ISSUE TITLE
add lemonsqueezy payment support

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#16]
Open SaaS currently has subscription payments via Stripe.

It would be nice to add similar support for [Lemon Squeezy](https://www.lemonsqueezy.com/) as mentioned by @shengxinjing

### Process

- move the action `stripePayment` from `app/src/server/actions.ts` to `app/src/server/stripeUtils.ts`
- create a similar file for lemonsqueezy, e.g. `app/src/server/lemonsqueezyUtils.ts` and add the complimentary checkout logic for lemon squeezy. If possible, we want to make the checkout action interchangeable with the `stripePayment` action, so that these actions can swapped 1:1 on the client
- create a complimentary webhook file in `app/src/server/webhooks` if necessary.
- update `app/src/client/app/PricingPage.tsx` if necessary

**Comment by shengxinjing** [comment]
I'm glad to be included in the development plan. I cloned the code but didn't see package.json. How did you develop and debug it?

**Comment by vincanger** [comment]
> I'm glad to be included in the development plan. I cloned the code but didn't see package.json. How did you develop and debug it?

That's expected. All the instructions for starting the template are here --> https://docs.opensaas.sh/start/getting-started/

**Comment by E5GEN2** [comment]
Subscribed

**Comment by LouisDeconinck** [comment]
LemonSqueezy would be a great addition!

**Comment by Antexa** [comment]
@vincanger any plan to release this feature ?

**Comment by vincanger** [comment]
@Antexa @LouisDeconinck @E5GEN2 We have someone working on it at the moment. check out the related conversation in our discord https://discord.com/channels/686873244791210014/1253294755207577732
