### ISSUE TITLE
Drop (or modify) the suggestion to update your open-saas app

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#161]
Related Discord question: https://discord.com/channels/686873244791210014/1245765686178087085/1245765686178087085 .

But, since the template is getting more complex and we dropped direct copying of it and instead are going with `wasp new -t`, we should probably also stop suggesting just pulling in the changes via git. I think those are not very useful anyway, since one wouldn't expect to be updating their template much: there could be significant drift due to either improvements on open-saas side, or because they modified the template a lot, it would have to be a somewhat specific situation to be able to do a nice update. And anyway open-saas is here to be a starter, not a library that you update.

**Comment by vincanger** [comment]
ok @Martinsos i know you told me to drop my lawless, cowboy coding ways, but i've just gone ahead and pushed / deployed this change in commit c3066842a270df94f87ad95d4611a1855e83a732
