### ISSUE TITLE
SendGris Issue

### ISSUE THREAD

**Issue by danjeldurmo** [wasp-lang/open-saas#162]
Hi all, 

when i try to send mail (verification or password reset) using SendGrid an error occurred:

`[ Server!] Failed to send email ResponseError: Forbidden
[ Server!]     at /Users/danjeldurmo/Desktop/data-app/app/node_modules/@sendgrid/client/src/classes/client.js:146:29
[ Server!]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[ Server!]   code: 403,
[ Server!]   response: {
[ Server!]     headers: {
[ Server!]       server: 'nginx',
[ Server!]       date: 'Sun, 02 Jun 2024 00:31:55 GMT',
[ Server!]       'content-type': 'application/json',
[ Server!]       'content-length': '281',
[ Server!]       connection: 'close',
[ Server!]       'access-control-allow-origin': 'https://sendgrid.api-docs.io',
[ Server!]       'access-control-allow-methods': 'POST',
[ Server!]       'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
[ Server!]       'access-control-max-age': '600',
[ Server!]       'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',
[ Server!]       'strict-transport-security': 'max-age=600; includeSubDomains'
[ Server!]     },
[ Server!]     body: { errors: [Array] }
[ Server!]   }
[ Server!] }`

in main.wasp i have correctly write my email:

`
email: {
        fromField: {
          name: "Open SaaS App",
          email: "info@datanext.app" 
        },

emailSender: {
    // Note that the "Dummy" provider is just for local development purposes. 
    // Make sure to check the server logs for the confirmation email token (it will not be sent to an address)!
    // Please use SendGrid in production. See: https://docs.opensaas.sh/guides/email-sending/
    provider: SendGrid, 
    defaultFrom: {
      name: "Open SaaS App",
      // When using SendGrid, you must use the same email address that you configured your account to send out emails with!
      email: "info@datanext.app" 
    },
  },
`

Could someone please help me to identify the problem?
In SendGrid i have select the second one when i read 'excludind email address validation' , Is correct?

![Screenshot 2024-06-02 alle 02 36 55](https://github.com/wasp-lang/open-saas/assets/66755329/da2dfc42-264c-47fb-8613-53cb6c6f8ccd)

**Comment by danjeldurmo** [comment]
Need do configurate a "Single Sender Verification" before to start

**Comment by m4ary** [comment]
I ran into the same problem by updating the email inside the auth block.

It might be helpful to mention this step in the documentation to avoid confusion for others.

**Comment by Martinsos** [comment]
> I ran into the same problem by updating the email inside the auth block.
> 
> It might be helpful to mention this step in the documentation to avoid confusion for others.

Thanks for the feedback! Woudl you be interested into making a PR that adds that to the docs?

**Comment by m4ary** [comment]
> > I ran into the same problem by updating the email inside the auth block.
> > It might be helpful to mention this step in the documentation to avoid confusion for others.
> 
> Thanks for the feedback! Woudl you be interested into making a PR that adds that to the docs?

sorry my bad ,  its already exist but i didn't see it  

![Image](https://github.com/user-attachments/assets/a21282b5-d772-4a50-bd44-5496f6e78dd3)

**Comment by Martinsos** [comment]
> > [@m4ary](https://github.com/m4ary) no worries! Should we try to make it more visible somehow?
> 
> Yeah, I think because of the green and red, readers tend to focus only on those changes and might think that’s all there is.

Right, make we should also make that line green! Would you like to create a PR for it?
