### ISSUE TITLE
Consider gitignoring package-lock.json in template/app and opensaas-sh/app(_diff)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#165]
I think it is best if we ignore it for template/app, it doesn't make much sense to me to bring it to the user of the template. And for demo app, we can keep it, to emulate normal usage, although it is not as important for a real app since it is a demo app, so it also might be tempting to drop it.

If gitignoring it for the template/app, we should do it from top level .gitignore, where we also ignore tempalte/app/migrations, since we don't want the users of our template to have package-lock.json ignored, only we want to ignore it.

**Comment by vincanger** [comment]
I don't understand why we'd want to remove package-lock.json from opensaas-sh? Since its effectively being used like a real app that people can test, shouldn't we keep it? or does it not make much difference?

**Comment by Martinsos** [comment]
Ok yeah makes sense! I meant, it is demo app, so we don't care that much about stability, but yeah let's treat it as a real app! All good, I agree -> we ignore it in template, we keep it in demo app.
