### ISSUE TITLE
`wasp db migrate-dev` throws an error

### ISSUE THREAD

**Issue by sammo** [wasp-lang/open-saas#166]
Hi - 

I'm trying to start a new wasp project but running into this error on `wasp db migrate-dev` command.

Do you know what the issue could be?

✅ --- Database successfully set up. ----------------------------------------------

🐝 --- Building SDK... ------------------------------------------------------------

[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '.../mySaasApp/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2

❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

**Comment by Martinsos** [comment]
@sammo this seems quite weird!

It could help if you could provide following info: your OS, wasp version, node version, how did you start the project (I guess from open-saas? Doing `wasp new -t saas`?).

In the meantime, pls try running `wasp clean` and see if that helps -> if it does, let us know.

**Comment by sammo** [comment]
@Martinsos thanks for the quick reply.
I'm using
* ubuntu 24.04
* wasp 0.13.2
* node 18.9.1

I started the project by running these commands:

```
curl -sSL https://get.wasp-lang.dev/installer.sh | sh
wasp new mySaasApp -t todo-ts
```

I'll `wasp clean`

**Comment by sammo** [comment]
@Martinsos I just ran `wasp new -t saas` and it worked!

**Comment by Martinsos** [comment]
Great @sammo ! I am still curious what caused the initial issue, do you have any idea? How did you create the project first time?

**Comment by sammo** [comment]
@Martinsos I found out from my .zsh_history this error was raised by `wasp db migrate-dev`

That's how I replicated it

```
wasp new mySaasApp2 -t todo-ts
cd mySaasApp2
wasp db migrate-dev
```

And I got this error

```
🐝 --- Compiling wasp project... --------------------------------------------------

[  Wasp  ] Starting npm install
[  Wasp  ] Still installing npm dependencies!
[  Wasp  ] Installation going great - we'll get there soon!
[  Wasp !] npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
[  Wasp !] npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
[  Wasp  ] 
[  Wasp  ] added 462 packages, and audited 463 packages in 18s
[  Wasp  ] 
[  Wasp  ] 101 packages are looking for funding
[  Wasp  ]   run `npm fund` for details
[  Wasp  ] 
[  Wasp  ] 2 moderate severity vulnerabilities
[  Wasp  ] 
[  Wasp  ] Some issues need review, and may require choosing
[  Wasp  ] a different dependency.
[  Wasp  ] 
[  Wasp  ] Run `npm audit` for details.
[ Client ] Starting npm install
[ Server ] Starting npm install
[ Client ] 
[ Client ] added 117 packages, and audited 118 packages in 3s
[ Client ] 
[ Client ] 14 packages are looking for funding
[ Client ]   run `npm fund` for details
[ Client ] 
[ Client ] found 0 vulnerabilities
[ Server ] Still installing npm dependencies!
[ Server!] npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[ Server!] npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[ Server!] npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[ Server ] 
[ Server ] added 372 packages, and audited 373 packages in 6s
[ Server ] 
[ Server ] 121 packages are looking for funding
[ Server ]   run `npm fund` for details
[ Server ] 
[ Server ] 4 moderate severity vulnerabilities
[ Server ] 
[ Server ] To address all issues (including breaking changes), run:
[ Server ]   npm audit fix --force
[ Server ] 
[ Server ] Run `npm audit` for details.
✅ --- Successfully completed npm install. ----------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


[   Db  !] Error: P1003
[   Db  !] 
[   Db  !] Database dev.db does not exist at /.../mySaasApp2/.wasp/out/db/./dev.db
[   Db  !] 
[   Db   ] Environment variables loaded from .env
[   Db   ] Prisma schema loaded from ../db/schema.prisma
[   Db   ] 
[   Db   ] ✔ Generated Prisma Client (4.16.2 | library) to ./../../../node_modules/@prisma/client in 63ms
[   Db   ] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[   Db   ] ```
[   Db   ] import { PrismaClient } from '@prisma/client'
[   Db   ] const prisma = new PrismaClient()
[   Db   ] ```
✅ --- Database successfully set up. ----------------------------------------------


🐝 --- Building SDK... ------------------------------------------------------------


[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '/.../mySaasApp2/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2
```


❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found
```

**Comment by Martinsos** [comment]
Awesome thanks! Just to confirm, this are not logs from the first time, you actually managed to replicate this again?

I wonder if this has something to do with node 18 hm, we will be looking into it.
