### ISSUE TITLE
e2e tests failing with cookie banner check

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#174]
![image](https://github.com/wasp-lang/open-saas/assets/1536647/f8a03136-90cb-45b4-8935-fb8bfc42bf65)

E2e tests often fail on cookie banner test since we added it. It seems to be flaky because it can help if we restart the github action.

Btw that assertion that fails, I would also rewrite it to be `expect(gaCookiesArr.length).toBe(2)` (made it up a bit but I am sure something like this is doable), so we get more info when the test fails.

**Comment by vincanger** [comment]
fixed in https://github.com/wasp-lang/open-saas/pull/176
