### ISSUE TITLE
Stripe Integration, address and Name

### ISSUE THREAD

**Issue by rugs07** [wasp-lang/open-saas#175]
As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports, This is the error, gone through docs https://docs.stripe.com/api/customers/create, still not solved. Can anyone guide which function to change so It gets the customer name and address dynamically?

**Comment by Martinsos** [comment]
@rugs07 what have you tried so far? I don't have the capacity to investigate this on the Stripe side nor do I know much about this specific problem with exports, but if you can narrow down this question to a more specific question about Wasp I might be able to help. It helps if you provide snippets of code in Wasp you have been looking at, what you tried, exact error, ...

**Comment by vincanger** [comment]
hey @rugs07 I've heard other devs from India saying that you need to turn `automatic_tax` to false within `app/src/server/payments/stripeUtils.ts`

Have you tried this?

**Comment by rugs07** [comment]
Yaa, I have tried this out and it works

**Comment by Martinsos** [comment]
Hm! SHoudl we add sometihng to the docs, or is this out of scope for OpenSaas, and more of a Stripe thing?

**Comment by vincanger** [comment]
ok thanks @rugs07 I'm closing this issue for now.
