### ISSUE TITLE
【feature request】lemon squeezy

### ISSUE THREAD

**Issue by wanghaisheng** [wasp-lang/open-saas#177]
can we add support for https://www.lemonsqueezy.com/ to speed up this great template for small teams that dont manage to get a stripe account

**Comment by vincanger** [comment]
it would be awesome if someone could take this on themselves. Would you be interested in submitting a PR for this @wanghaisheng ?

**Comment by vincanger** [comment]
closing this for now -- we have a related convo in our discord though https://discord.com/channels/686873244791210014/1253294755207577732
