### ISSUE TITLE
Mailgun should be set as provider in the example code of Mailgun under the "Integrate your email sender" section

### ISSUE THREAD

**Issue by KiDxS** [wasp-lang/open-saas#194]
As I was reading the documentation about email sending. I noticed that in the example code of Mailgun under the "integrate your email sender" section is set to `SendGrid`. 

![image](https://github.com/wasp-lang/open-saas/assets/43493935/68a71543-7b61-424d-8911-9a9a67ea91ba)

**Comment by vincanger** [comment]
cool. thanks for the heads up. fixed!
