### ISSUE TITLE
【Suggestion】 Specify the required basic configurations for this project.

### ISSUE THREAD

**Issue by godblessbb** [wasp-lang/open-saas#21]
The project lacks specific requirements, such as server system, which has made the compilation process very difficult. It is not as straightforward as described in the documentation, where it claims that it can be up and running with just a few lines of code. I'm unsure if this is due to my technical limitations, but I have made every effort to address all the encountered issues, only to find new problems continuously emerging.

**Comment by Martinsos** [comment]
@godblessbb sorry to hear that you had a hard time with the setup! Would you mind explaining which problems you had, so we can see what we can do, be it improving the docs or something else?

**Comment by godblessbb** [comment]
> @godblessbb sorry to hear that you had a hard time with the setup! Would you mind explaining which problems you had, so we can see what we can do, be it improving the docs or something else?

I am currently trying to install this project on my CentOS 7 system. Due to the older version of glibc, I have to use a Docker container with Rust installed to run this project. Somehow, this process is filled with errors. I have to manually install all the dependencies because using "wasp start" always results in errors. However, even the manual installation process is often interrupted by various errors, indicating potential version conflicts. It would be helpful if the project documentation clearly stated some basic version requirements, which could potentially save some time. This is just a friendly suggestion as I continue to struggle with these errors.

**Comment by godblessbb** [comment]
@Martinsos Hello Martin, I have to say that Wasp doesn't seem to be as user-friendly as expected. I have to give up this project. Although I am a beginner, I can easily locate errors and make improvements in other languages. However, with Wasp, it always provides ambiguous hints that require me to guess, and sometimes the error messages do not match the actual solutions. I hope you can develop a more user-friendly version. I have already spent two weeks on this project, and it has been too painful.

**Comment by Martinsos** [comment]
@godblessbb I am sorry to hear that -> it is true that we don't have a binary specifically built for CentOS 7, and I understand that makes installation harder for you. Wasp is a project in Beta and we are working hard to bring it to 1.0 and be easy to use for everyone, but there is a lot of work still ahead of us. Thanks for giving it a try and good luck!
