### ISSUE TITLE
Add Lemon Squeezy Payment Integration for Subscription Support

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [wasp-lang/open-saas#213]
Hi,

Thank you for creating and maintaining this fantastic repository!

However, I have encountered an issue where Stripe is not supported in my country, which makes it difficult for me to utilize the subscription payment feature. To address this, I would like to suggest integrating Lemon Squeezy as an alternative payment gateway for subscription management.

**Lemon Squeezy** is a reliable and developer-friendly payment platform that supports a wide range of countries and offers robust subscription handling features.

Would it be possible to implement Lemon Squeezy as an additional payment option alongside Stripe? This would greatly enhance the accessibility of the project for users in countries where Stripe is not available.

Thank you for considering this request, and I am looking forward to your response.

**Comment by Martinsos** [comment]
We do actually have an issue for this! https://github.com/wasp-lang/open-saas/issues/103. we also have a contributor workign on it,so we might have a PR soon!
