### ISSUE TITLE
refactor our `userSignupFields` to use the new AuthUser identity properties in v014

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#231]
currently we assign `email` and `username` to the `User` entity via our `userSignupFields.ts` custom signup functions. But now, in v0.14, we can instead directly access these properties on the auth user, e.g. 

```ts
import { AuthUser } from 'wasp/auth'

const MainPage = ({ user }: { user: AuthUser }) => {
  const email = user.identities.email?.id
  // ...
}
```

**Comment by Martinsos** [comment]
There is however a pro to assigning `email` and `username` directly to `User` entity: it is somewhat easier to access later, we can access it even if `user.identities` haven't been populated, and also we don't have to constantly deal with specific of each provider/identity when trying to get an email / username.
I am not saying we shouldn't do the change you proposed here, but I am saying I am not sure if we should do it.

It's a bit complicated topic and we are still figuring out the best practices about it, here is the issue for figuring out and documenting them: https://github.com/wasp-lang/wasp/issues/2034 .

@infomiho FYI.

**Comment by vincanger** [comment]
ok this is a good point, Martin. Closing this for now.
