### ISSUE TITLE
Cannot compile a new file

### ISSUE THREAD

**Issue by jasoncysiu** [wasp-lang/open-saas#235]
Hi, 
First of all, Kudos to @vincanger and community for the amazing work. It looks cool! 

I am new to React and OpenSaas. When I added a new .tsx file under `src\client\app\MainPage.tsx`, and added the following route in main.wasp:

route MainPageRoute { path: "/MainPage", to: MainPage }
page MainPageRoute {
  component: import MainPage from "@src/client/app/MainPage"
}

Problem: I cannot compile the file after adding this code. I wonder what I did wrong.

Error:

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- /app/main.wasp @ 149:46-53
  Type error:
    Undefined identifier: MainPage

     148 |
     149 | route MainPageRoute { path: "/MainPage", to: MainPage }
     150 | page MainPageRoute {

**Comment by Martinsos** [comment]
Hey, thanks for the kind words :)!

Your `route` is referencing `MainPage`, but you by accident also named your page `MainPageRoute`, so there is no identifier `MainPage`.

Fix:
```js
route MainPageRoute { path: "/MainPage", to: MainPage }
page MainPage {
component: import MainPage from "@src/client/app/MainPage"
}
```

**Comment by jasoncysiu** [comment]
Fantastico! It works like charm :) Thanks @Martinsos!
