### ISSUE TITLE
Update `BarChart` to work with latest `apexcharts` update

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/open-saas#241]
Users [reported in Discord](https://ptb.discord.com/channels/686873244791210014/1264691828654080072/1264691828654080072) Typescript errors when using the latest Open SaaS:

<img width="853" alt="Screenshot 2024-07-22 at 10 37 50" src="https://github.com/user-attachments/assets/e1d2962c-15ac-4747-9f72-8bca1dd27aae">

It's due to ApexCharts library we use for our charts made a breaking change in their types (removed the `radius` property we used in the options) but they bumped their version as a minor change: [v3.50.0](https://github.com/apexcharts/apexcharts.js/releases/tag/v3.50.0) -> [v3.51.0](https://github.com/apexcharts/apexcharts.js/releases/tag/v3.51.0) instead of major change so `npm` installed the next minor by default.

How we could fix it:
- We could update the template _not to use_ the `radius` property.
- We could use a specific version of ApexCharts to prevent uncontrolled version bumps.

Reported to ApexCharts here: https://github.com/apexcharts/apexcharts.js/issues/4580

**Comment by vincanger** [comment]
ok @infomiho I removed the radius property as it wasn't really necessary anyway and BarChart is just an unused example chart we ship with it. This should be enough for now
