### ISSUE TITLE
Can't run wasp several times at one time

### ISSUE THREAD

**Issue by melodyxpot** [wasp-lang/open-saas#249]
Hello everyone.
I am a wasp beginner and I was going to use it to run opensaas project.
I successfully installed the project and was about to start it.
I could run `wasp start db` but after that, I couldn't run `wasp` command anymore including `wasp db migrate-dev`.

![image](https://github.com/user-attachments/assets/8473b51f-8086-4abf-bed0-87c2576d0d6a)
![image](https://github.com/user-attachments/assets/34e09ef4-4ba7-482a-b691-336eb98542d4)

What happened? Does anyone know the solution?
If there is, Please help me.
So much appreciate it.
Thank you.

**Comment by sodic** [comment]
I'm guessing you're missing Wasp in your `PATH` variable.

I'll close this issue since it doesn't seem related with OpenSaas.

Can you jump into our Discord server and ask the question in the #questions channel, and I'll help you out there.
