### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by hellwaiver** [wasp-lang/open-saas#268]
Documentation states the webhook lives at 

localhost:3001/payments-webhook (https://docs.opensaas.sh/guides/payments-integration/)

It's actually at

http://localhost:3001/stripe-webhook

**Comment by vincanger** [comment]
We've actually updated the docs and code, so yes for older versions of the template, it's `stripe-webhook` but for the current version it is `payments-webhook` since we've also introduced Lemon Squeezy

**Comment by vincanger** [comment]
@hellwaiver i've updated the docs to reflect this change https://docs.opensaas.sh/guides/payments-integration/#install-the-stripe-cli
