### ISSUE TITLE
Local login is not working 

### ISSUE THREAD

**Issue by MiqueiasGFernandes** [wasp-lang/open-saas#27]
When I execute open-saas from command "wasp start" and following settings at main.wasp:
The compile process returns to me this error:
[https://gist.github.com/MiqueiasGFernandes/365a800aa7a1a5b091aad89745be7fc2](Gist URL)
`➜  app git:(main) ✗ wasp start

🐝 --- Starting compilation and setup phase. Hold tight... ------------------------

🐝 --- Compiling wasp project... --------------------------------------------------

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- Expected app.auth to use either email or username and password authentication, but not both.
- Entity 'User' (referenced by app.auth.userEntity) must have field 'password' of type 'String'.

❌ --- [Error] Compilation of wasp project failed: --------------------------------

2 errors found`

**Comment by vincanger** [comment]
Hey @MiqueiasGFernandes the errors are telling you what to do:
- ` use either email or username and password authentication, but not both`

If you want to just use `usernameAndPassword` auth to get started, change the `main.wasp` file to look like this:

```
//...
  auth: {
    userEntity: User,
    externalAuthEntity: SocialLogin,
    methods: {
      usernameAndPassword: {}
    }, 
    //...
```
 Note that `usernameAndPassword` should not be used in production and won't work with Stripe checkout.
 
 For production, switch to `email` or social auth, and try making the `email`, `username`, and `password` fields of your user entity optional (`?`), like this:

```
entity User {=psl
  id                        Int             @id @default(autoincrement())
  email                     String?         @unique
  username                  String?         @unique
  password                  String?
  //...
  ```
  We have a whole section in the docs about migrating the Auth methods: https://docs.opensaas.sh/guides/authentication/#migrating-to-a-different-auth-method
  
  Let me know if that works! :)

**Comment by Martinsos** [comment]
Closing this for now as it looks to me like solution is clear, but @MiqueiasGFernandes please do comment again if that is not so!
