### ISSUE TITLE
Web App Client deploy fails from Github Actions

### ISSUE THREAD

**Issue by optimizerbuddy** [wasp-lang/open-saas#276]
Client, Server, DB all deploys correctly from local machine. But client deployment fails when running from Github actions.

Nothing fancy on the deployment script, same command used to deploy from local machine.

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s -- -v ${{ env.WASP_VERSION }}

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Cache global node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('app/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}-wasp${{ env.WASP_VERSION }}-node${{ steps.setup-node.outputs.node-version }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Deploy
        working-directory: .
        run: |
          cd app
          wasp deploy fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

`

Any idea why the server deployment succeeds but the client fails?

Excerpt from the github actions log below

🚀  Server has been deployed! 
🚀  Deploying your client now... 
🚀  Building web client for production... 
$ cd /home/runner/work/framework/framework/app/.wasp/build/web-app
$ npm install

added 1 package, and audited 111 packages in 569ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ REACT_APP_API_URL=https://optimizer-buddy-app-server.fly.dev/ npm run build

 OptimizerBuddy@0.0.0 build
 npm run validate-env && tsc && vite build

 OptimizerBuddy@0.0.0 validate-env
 node -r dotenv/config ./scripts/validate-env.mjs

🔍 Validating environment variables...
vite v5.4.8 building for production...
transforming...

./images/icon/icon-calendar.svg referenced in ./images/icon/icon-calendar.svg didn't resolve at build time, it will remain unchanged to be resolved at runtime

./images/icon/icon-arrow-down.svg referenced in ./images/icon/icon-arrow-down.svg didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 392 modules transformed.
rendering chunks...
computing gzip size...
build/index.html                                  2.02 kB │ gzip:   0.80 kB
build/assets/avatar-placeholder-BDh590iI.png      9.43 kB
build/assets/logo-MxRiw5HA.png                   10.97 kB
build/assets/banner-C6HNWtzi.png              1,173.15 kB
build/assets/index-BXqiiJ0D.css                 100.01 kB │ gzip:  17.00 kB
build/assets/index-dw-nNt9B.js                1,178.28 kB │ gzip: 331.55 kB

(!) Some chunks are larger than [500](https://github.com/optimizerbuddy/framework/actions/runs/11108481087/job/30861525174#step:8:501) kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 8.04s
$ flyctl deploy --remote-only
==> Verifying app config
--> Verified app config
Validating /home/runner/work/framework/framework/app/.wasp/build/web-app/fly.toml
✓ Configuration is valid
Error: Could not find App "optimizer-buddy-app-client"
file:///home/runner/.local/share/wasp-lang/0.14.0/data/packages/deploy/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

Error: Output [Error]: ==> Verifying app config
--> Verified app config
Error: Could not find App "optimizer-buddy-app-client"
    at deployClient (file:///home/runner/.local/share/wasp-lang/0.14.0/data/packages/deploy/dist/providers/fly/deploy/deploy.js:92:13)
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/runner/.local/share/wasp-lang/0.14.0/data/packages/deploy/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: 'Validating /home/runner/work/framework/framework/app/.wasp/build/web-app/fly.toml\n' +
    '\x1B[32m✓\x1B[0m Configuration is valid\n',
  _stderr: '==> Verifying app config\n' +
    '--> Verified app config\n' +
    'Error: Could not find App "optimizer-buddy-app-client"\n',
  _combined: '==> Verifying app config\n' +
    '--> Verified app config\n' +
    'Validating /home/runner/work/framework/framework/app/.wasp/build/web-app/fly.toml\n' +
    '\x1B[32m✓\x1B[0m Configuration is valid\n' +
    'Error: Could not find App "optimizer-buddy-app-client"\n'
}

Node.js v20.17.0

Error: Error] Deploy command failed: ---------------------------------------------

Deploy command failed with exit code: 1
Error: Process completed with exit code 1.

**Comment by Martinsos** [comment]
@optimizerbuddy thanks on detailed error logs!

Error seems to be:
> Error: Could not find App "optimizer-buddy-app-client"

Meaning, if I am correct, that Fly couldn't find the app with that name up there on Fly.

Can you check what is the name you app uses on Fly? If it is this same name, than that would be very weird, but if it is somewhat different name, then we can look into why the names are different.

I am guessing it might be connected to this issue https://github.com/wasp-lang/wasp/issues/1588, and the difference between your local usage and cloud (GH Actions) might be due to different flycli versions (can you check their versions also?).

**Comment by vincanger** [comment]
closing this for now. @optimizerbuddy let us know if you need more help and we can reopen.
