### ISSUE TITLE
Critical vulnerability in Wasp's use of outdated Mailgun library

### ISSUE THREAD

**Issue by infovs** [wasp-lang/open-saas#308]
Wasp's built-in use of Mailgun appears to be outdated and it introduces a critical vulnerability per NPM.
The specific dependency that is the issue is netmask@1.0.6

netmask  <=2.0.0
Severity: critical
Improper parsing of octal bytes in netmask - https://github.com/advisories/GHSA-4c7m-wxvm-r7gc
netmask npm package mishandles octal input data - https://github.com/advisories/GHSA-pch5-whg9-qr2r
No fix available
node_modules/pac-resolver/node_modules/netmask

The dependency is nested in wasp's SDK per below:

└─┬ wasp@1.0.0 -> ./.wasp/out/sdk/wasp
  **└─┬ ts-mailgun@0.5.1**
    └─┬ mailgun-js@0.22.0
      └─┬ proxy-agent@3.1.1
        └─┬ pac-proxy-agent@3.0.1
          └─┬ pac-resolver@3.0.0
            └── netmask@1.0.6

ts-mailgun is not actively maintained.

The correct fix therefore seems to be updating the sdk to use the mailgun.js library which is actively maintained.

**Comment by vincanger** [comment]
@infomiho i think this is meant for the wasp repo but thought i'd ping you here first.

**Comment by infomiho** [comment]
Since Wasp 0.15.0, we are no longer using the `ts-mailgun` library for handling sending emails with Mailgun: https://github.com/wasp-lang/wasp/pull/2303
