### ISSUE TITLE
Update Node to latest LTS (20.9.0)

### ISSUE THREAD

**Issue by fantapop** [wasp-lang/open-saas#31]
I see there is a new LTS for node as of a few months ago. https://nodejs.org/en/blog/release/v20.9.0

Based on the wording [here](https://wasp-lang.dev/docs/quick-start#requirements) it looks like you're trying to keep up with the latest LTS so its probably time to upgrade.

**Comment by vincanger** [comment]
@fantapop this is a main wasp issue, and I believe this is being addressed in the [upcoming 0.12 release](https://github.com/wasp-lang/wasp/releases), which should be officially released in the next day or two. In the meantime, you can just use NVM to switch to node v18.

**Comment by Martinsos** [comment]
Yes, this is coming very very soon! Thanks for the comment!
