### ISSUE TITLE
AWS File upload to S3 - add a progress bar?

### ISSUE THREAD

**Issue by tazzouni** [wasp-lang/open-saas#313]
The file upload functionality works like a charm!

However, when trying to upload a large file the frontend would instantly shows you that the file is "uploaded" even though it is still uploading in the backend. which could be confusing. perhaps a progress bar would be helpful?

![waspFileUpload](https://github.com/user-attachments/assets/d0a1329d-2fba-464b-87ef-4508d2412864)

**Comment by Martinsos** [comment]
Yes certainly! Or if not progress bar, which can be a bit tricky since we need to get info on how upload is progressing, then at least a spinner/loader of a sort, to show that upload is in progress.

**Comment by vincanger** [comment]
Hey @tazzouni are you actively working on a solution for this issue? If so, I will assign you to this issue for now. :)

**Comment by vincanger** [comment]
@tazzouni I've started working on this (https://x.com/hot_town/status/1856680286538338745). PR will be incoming here shortly.
