### ISSUE TITLE
Self-Signed Cert in the Keychain

### ISSUE THREAD

**Issue by YoungFizzler** [wasp-lang/open-saas#316]
I'm trying to run sudo wasp db migrate-dev however I get the errors below:

`[   Db  !] Error: request to https://binaries.prisma.sh/all_commits/69d742ee20b815d88e17e54db4a2a7a3b30324e3/darwin-arm64/libquery_engine.dylib.node.sha256 failed, reason: unable to get issuer certificate
[   Db  !] Error: request to https://binaries.prisma.sh/all_commits/69d742ee20b815d88e17e54db4a2a7a3b30324e3/darwin-arm64/libquery_engine.dylib.node.gz.sha256 failed, reason: unable to get issuer certificate`

I'm 100% sure it's because I have a self-signed certificate which is required for my network to work. It's a CA certificate. 

What can I do to fix this? Is there any CLI arguments I can pass?

**Comment by Martinsos** [comment]
> Normally with tools they have CLI arguments to allow self-signed certificates. I am just wondering if Wasp-Lang has something like this?

No it doesn't, but I would be surprised if that is something we should support. Maybe I don't know enough about it though. Can you please give me some examples of such tools and situtations in which they allow for specifying such CLI arguments?

Also, what does `wasp start` do for you?

**Comment by YoungFizzler** [comment]
https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate
https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi
https://stackoverflow.com/questions/34498736/npm-self-signed-cert-in-chain

I'll update you with the `wasp start` later when I can get to my PC!

**Comment by Martinsos** [comment]
@YoungFizzler thanks for sharing this, this gives me a better idea of what this is about!

I am not 100% sure, but I believe the error you get from Wasp is actually coming from `npm` -> Wasp is asking npm to install prisma stuff, and npm fails. You could check the logs around that error for extra infromatino to possibly confirm this. Solution therefore would be to look into solutions for `npm`, and while you can't pass cmd line params, you can set env vars, or you can configure npm globally. I see some such solutions proposed here https://stackoverflow.com/questions/34498736/npm-self-signed-cert-in-chain .

Let me know if this helped! If not, and you could use more help from my side, please share more logs around the error you get, that might help me out, and also `wasp start` output as I mentioned before, that also might give me some more ideas at which exactly part is stuff failing.
