### ISSUE TITLE
Error code ERESOLVE for wasp dp migrate-db

### ISSUE THREAD

**Issue by papapon** [wasp-lang/open-saas#336]
Hello,

I'm trying to create a new project from an open saas template (option 3 in wasp new). When wasp db migrate-dev, I encounter the following problem: 

🐝 --- Compiling wasp project... --------------------------------------------------

[  Wasp  ] Starting npm install
[  Wasp  ] Still installing npm dependencies!
[  Wasp !] npm ERR! code ERESOLVE
[  Wasp !] npm ERR! ERESOLVE unable to resolve dependency tree
[  Wasp !] npm ERR!
[  Wasp !] npm ERR! While resolving: opensaas@undefined
[  Wasp !] npm ERR! Found: apexcharts@3.54.1
[  Wasp !] npm ERR! node_modules/apexcharts
[  Wasp !] npm ERR!   apexcharts@"^3.41.0" from the root project
[  Wasp !] npm ERR!
[  Wasp !] npm ERR! Could not resolve dependency:
[  Wasp !] npm ERR! peer apexcharts@">=4.0.0" from react-apexcharts@1.6.0
[  Wasp !] npm ERR! node_modules/react-apexcharts
[  Wasp !] npm ERR!   react-apexcharts@"^1.4.1" from the root project
[  Wasp !] npm ERR!
[  Wasp !] npm ERR! Fix the upstream dependency conflict, or retry
[  Wasp !] npm ERR! this command with --force or --legacy-peer-deps
[  Wasp !] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[  Wasp !] npm ERR!
[  Wasp !] npm ERR!
[  Wasp !] npm ERR! For a full report see:
[  Wasp !] npm ERR! /home/papapon/.npm/_logs/2024-11-29T09_24_23_846Z-eresolve-report.txt
[  Wasp !]
[  Wasp !] npm ERR! A complete log of this run can be found in: /home/papapon/.npm/_logs/2024-11-29T09_24_23_846Z-debug-0.log

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- npm install failed: Project setup failed with exit code 1.

❌ --- [Error] Compilation of wasp project failed: --------------------------------

Whether I'm testing with wsl on windows or debian, I have the same problem. 

Wasp version : 0.15.2

**Comment by vince-alcivar** [comment]
Facing this same issue. Not sure how to get around this.

**Comment by vincanger** [comment]
Whoops! sorry about that @papapon. Thanks, @vince-alcivar, I've updated the template to use strict versioning for apex-charts. Let us know if you have any other questions--[discord](https://discord.gg/rzdnErX) is best. Happy building!
