### ISSUE TITLE
Client-server communication

### ISSUE THREAD

**Issue by danjeldurmo** [wasp-lang/open-saas#34]
Hello everyone, first of all congratulations for the work done.

Maybe I'm too ignorant :( but I can't understand how the communication between clinet and server takes place in your project managed with wsap.

For example, if I wanted to create a page where on the client side if the user types red the server replies "you won", if he types any other word the server replies "you lost". How should this be implemented?

I created the page src/server/api-google.ts:

`export const searchGoogle = async ({ query }) => {
    if (query === "red") {
        console.log("you won");
        return "you won";
    } else {
        console.log("you lost");
        return "you lost";
    }
};
`

and the page src/client/app/SearchGooglePage.tsx:

`import React, { useState } from 'react';
import api from '@wasp/api';

const SearchGooglePage = () => {
  const [searchQuery, setSearchQuery] = useState('');

  const handleSearch = async (event) => {
    event.preventDefault();
    try {
      const result = await api.searchGoogle({ query: searchQuery });
      alert(result);
    } catch (error) {
      console.error('Search failed:', error);
      alert('Search failed, please try again.');
    }
  };

  return (
    <div className="container mx-auto px-4">
      search
      <form onSubmit={handleSearch} className="mt-4">
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Digita qui per cercare..."
          className="px-4 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-yellow-500"
        />
        <button
          type="submit"
          className="ml-4 px-4 py-2 bg-yellow-500 text-white rounded-md shadow hover:bg-yellow-600"
        >
          Cerca
        </button>
      </form>
    </div>
  );
};

export default SearchGooglePage;
`

and in main.wasp i have added:

`api searchGoogle {
  fn: import { searchGoogle } from "@ext/api-google.js"
}
`

But nothing happens :( could you help me understand this? If I can do this simple exercise I will be able to understand more how client-server communicate.

Many thanks

**Comment by vincanger** [comment]
Hey @danjeldurmo 

The default way to communicate between client and server is via [Operations](https://wasp-lang.dev/docs/data-model/operations/overview) (defining an `api` in Wasp is for custom HTTP endpoints -- you don't need this in your case)

your code should rather look like this:

```ts 
// main.wasp 

query checkIfRed {
  fn: import { checkIfRed } from "@server/queries.js"
} 
```

```ts
// src/server/queries.ts

import { CheckIfRed } from '@wasp/queries/types'

export const checkIfRed: CheckIfRed<string, string> = (color, context) => {
  if (color !== 'red') { 
    return 'you lose'
  } else {
    return 'you win'
  }
}
```

```tsx
// MainPage.tsx

import { useQuery } from '@wasp/queries'
import checkIfRed from '@wasp/queries/checkIfRed'

const MainPage = () => {
  const [color, setColor] = useState('red')

  // TypeScript will automatically infer and type-check payload types.
  const { data: answer, error, isLoading } = useQuery(checkIfRed, color)
  
  //...
```

i'm closing this issue for now since this is pretty straightforward and documented thoroughly in the [docs](https://wasp-lang.dev/docs/data-model/operations/overview), but let me know if you have any other Qs

**Comment by danjeldurmo** [comment]
Thank you very much for the reply, I tried to follow all the steps but unfortunately I only see a blank page 🙂

```
// main.wasp

route checkIfRedRoute { path: "/red", to: checkIfRedPage }
page checkIfRedPage {
  authRequired: true,
  component: import checkIfRedPage from "@client/app/checkIfRedPage"
}

query checkIfRed {
  fn: import { checkIfRed } from "@server/queries.js"
} 
```
```
// src/server/queries.ts

import { CheckIfRed } from '@wasp/queries/types'

export const checkIfRed: CheckIfRed<string, string> = (color, context) => {
  if (color !== 'red') { 
    return 'you lose'
  } else {
    return 'you win'
  }
};
```
```
// checkIfRedPage.tsx

import React, { useState } from 'react';
import { useQuery } from '@wasp/queries'
import checkIfRed from '@wasp/queries/checkIfRed'

const MainPage = () => {
  const [color, setColor] = useState('red')


  const { data: answer, error, isLoading } = useQuery(checkIfRed, color)
  
};
```
But page checkIfRedPage.tsx stay blank 

![Screenshot 2024-02-09 alle 00 11 42](https://github.com/wasp-lang/open-saas/assets/66755329/40030747-cc78-464c-a04c-0e7c56c1d4d5)

If i put a simple code it's work

![Screenshot 2024-02-09 alle 00 14 44](https://github.com/wasp-lang/open-saas/assets/66755329/82683ed7-833d-4c6e-9e86-03f9535f49df)
