### ISSUE TITLE
getDailyStats `HttpError` being thrown with invalid status code

### ISSUE THREAD

**Issue by tconroy** [wasp-lang/open-saas#344]
in [analytics/operations.ts#LN27](https://github.com/wasp-lang/open-saas/blob/6e41a1032a95365fee835dc5e02ea433fd986ba7/template/app/src/analytics/operations.ts#L27) there is a `throw new HttpError(204, 'No daily stats generated yet.');`

When deployed, this throws repeatedly:
```
Error: statusCode has to be integer in range [400, 600).
    at HttpError (/app/.wasp/out/sdk/wasp/server/HttpError.ts:15:13)
    at getDailyStats$2 (/app/src/analytics/operations.ts:27:11)
    at <anonymous> (/app/.wasp/build/server/src/middleware/operations.ts:14:24)
    at <anonymous> (/app/.wasp/out/sdk/wasp/server/utils.ts:26:5)
```

Based on the error, it appears `HttpError` in Wasp enforces a status code >= 400 && <= 600:
https://github.com/wasp-lang/wasp/blob/f2b966ad44012809b3141b2083e2368c31ed0bb1/waspc/data/Generator/templates/sdk/wasp/server/HttpError.ts#L14-L16

**Comment by tconroy** [comment]
One recommendation could be to replace this implementation with a more generalized HTTP Error library. [http-errors](https://github.com/curveball/http-errors/tree/main) is well supported and covers a variety of usecases.

**Comment by vincanger** [comment]
Good find @tconroy. I created a fix for this in the PR above if you're interested
