### ISSUE TITLE
Example deploy and set secrets for fly

### ISSUE THREAD

**Issue by mbordash** [wasp-lang/open-saas#348]
Hi, 

I've had an exceptional experience developing on the opensaas template. All is working well in dev, however, when it comes time to deploy to Fly using a custom domain, I'm having many difficulties getting my Google Auth to function.  I've setup the google auth callbacks, certificates, but I think I'm not setting the build env variables properly and when to call set secrets, especially when it comes to WASP_WEB_CLIENT_URL, WASP_SERVER_URL, REACT_APP_API_URL. Could you share working examples of how to deploy opensaas/wasp on fly so that I can compare with my own?

Thanks in advance,

Michael

**Comment by m3ta4** [comment]
@mbordash I'm getting a 401 now too. How did you resolve it for your build?
