### ISSUE TITLE
adding a custom route

### ISSUE THREAD

**Issue by bababuluba** [wasp-lang/open-saas#40]
Follow the instruction on docs to add a custom route. the response message not show up. it seems the  response message for every page is the same. How should adding a custom route? how to remove the default response message?

**Comment by Martinsos** [comment]
Hey, which custom route, one for frontend? `route MyRoute {...` in the main.wasp file?
Can you please share what you tried (code, both in main.wasp and in JS), what you expected and what happened, in more details?

**Comment by bababuluba** [comment]
Hi, thank you for response
this is what I follow https://wasp-lang.dev/docs/project/server-config#adding-a-custom-route
in main.wasp I add
```
  server:{
    setupFn: import { mySetupFunction } from "@server/myServerSetupCode.js",
  },
```
in myServerSetupCode.ts I add
```
import { ServerSetupFn, Application } from '@wasp/types'

export const mySetupFunction: ServerSetupFn = async ({ app }) => {
  addCustomRoute(app)
}

function addCustomRoute(app: Application) {
  app.get('/customRoute', (_req, res) => {
    res.send('I am a custom route')
  })
}
```

I got the response
![image](https://github.com/wasp-lang/open-saas/assets/31023757/5137c5fb-86af-41ca-a112-5b5ad82607cb)

**Comment by bababuluba** [comment]
what i actually want to do is to create a reverse proxy to the request on a route to my internal docker service like:

```
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');
const app = express();
const port = 3000;

// Proxy route to Docker service
app.use('/docker-service', createProxyMiddleware({ target: 'http://docker-service-host:docker-service-port', changeOrigin: true }));

app.listen(port, () => {
  console.log(`Node.js app listening at http://localhost:${port}`);
});
```

**Comment by bababuluba** [comment]
Hi @Martinsos , any thoughs?

**Comment by bababuluba** [comment]
done

**Comment by Martinsos** [comment]
Thanks @bababuluba ! Ah yes it is somewhat easy to get confused there if you jump to that file in the docs!
