### ISSUE TITLE
Fix "edit page" link in the docs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#44]
When in the docs of OpenSaas, there is "edit page" button but it gives me 404.

![image](https://github.com/wasp-lang/open-saas/assets/1536647/2cd5966d-44d3-4d3a-98ee-06f4149b2061)

**Comment by vincanger** [comment]
fixed 🌭

**Comment by rbatista191** [comment]
@vincanger can this button be removed? I am using it as a blog and would rather not show it.

**Comment by vincanger** [comment]
@rbatista191 that's a starlight feature. checking their docs it seems like all you have to do is remove the edit link property from astro's config file --> https://starlight.astro.build/guides/customization/#edit-links

**Comment by rbatista191** [comment]
> @rbatista191 that's a starlight feature. checking their docs it seems like all you have to do is remove the edit link property from astro's config file --> https://starlight.astro.build/guides/customization/#edit-links

Thanks @vincanger, solved!
