### ISSUE TITLE
In the docs, under "Getting Started", make it clear that `curl ...` is not for native windows

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#45]
There is a piece of code at "Getting Started" docs page that has `curl ...` command for installing Wasp, but it doesn't say that it is not for native Windows, but for Linux/Mac/WSL. We should mention this, so people don't try it on Windows and get stuck/confused (we had such cases, which is I am writing this).

![image](https://github.com/wasp-lang/open-saas/assets/1536647/16ca950a-6d3e-4e81-9343-ef56130f9d96)

**Comment by vincanger** [comment]
good catch. I think we can take care of this one along with issue #43 -- is that ok for you @martinovicdev ?

**Comment by martinovicdev** [comment]
Exactly, I just made a PR regarding this :D. It's the same issue.

**Comment by vincanger** [comment]
completed in pr #46
