### ISSUE TITLE
Keycloak integration

### ISSUE THREAD

**Issue by DanielKucal** [wasp-lang/open-saas#49]
Hello! Are there any plans/PoCs/plugins for using OpenSaaS with [KeyCloak](https://www.keycloak.org/)? Or contraindications to it?

**Comment by Martinsos** [comment]
Sorry for sending you to Discord, but we just discussed KeyCloak yesterday there: https://discord.com/channels/686873244791210014/1208050260698464307/1208050260698464307 .

TLDR: we will be adding support for [Arctic](https://github.com/pilcrowOnPaper/arctic) to Wasp in the next month, which will bring support for many oauth providers, including keycloak. OpenSaas is based on Wasp and will therefore also enable KeyCloak from that point on.

**Comment by vincanger** [comment]
hey @DanielKucal keycloak auth is now possible with Open SaaS / Wasp v0.13 https://github.com/wasp-lang/wasp/releases/tag/v0.13.0

closing this issue for now. let us know if you have any other questions!
