### ISSUE TITLE
Explicitly mention that developer should create a new `.env.server` file, and not use `.env.server.example`

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/open-saas#51]
Is that the idea, did I get it right? I got across this at https://docs.opensaas.sh/guides/authentication/#google-auth, where it is mentioned to add stuff to `.env.server` file, but we never created it in the first place. So I wasn't sure if I should create a new one, reuse the example one or sth else. Would be nice to have some tip about this.

**Comment by GavPierce** [comment]
I believe it is mentioned in the Docs -> Getting started:
![image](https://github.com/wasp-lang/open-saas/assets/75098765/fa4f82c0-e710-42c6-a03f-8ab1d9442544)

**Comment by vincanger** [comment]
yep! thanks @GavPierce 🙏

is that enough @matijaSos or do you think the instructions could be improved somehow?

**Comment by Martinsos** [comment]
What I did in `wasp new` is actually added a command to do it:
```
cp .env.server.example .env.server
```

I would consider doing that. I know for me, when reading docs, most of my focus goes on code to copy and execute :D, and less on text, and this way you make it really easy for me to do the right thing.
