### ISSUE TITLE
When I clone an open-saas repo, I start with 102 commits and 8 contributors. Also, how do I get updates?

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/open-saas#53]
Is this an intended way to start a new project, by cloning the open-saas repo? It is a bit strange to start out with 102 commits and 8 contributors to the project. I squashed all 102 commits into one, but I'm still left with the contributors.

Maybe that's the why to go, but I'm just wondering what would the best practice be. Another question is how I should apply updates to OS template - e.g. since I started there are 2 new commits that fix bugs. I guess I should just rebase on it.

Maybe adding a few sentences about this in the docs would be helpful.

**Comment by GavPierce** [comment]
I would also like to know a better way for onboarding users to use the project without just cloning the repo.

What if we add open-saas to a package directory like NPM?
What if WASP could also pull it in via the CLI and it installs the boilerplate code? `wasp create saas`.

**Comment by matijaSos** [comment]
now thinking about it, how about simply downloading the .zip file? That should be the files only, without any git history, right?

**Comment by GavPierce** [comment]
Yes that would work. 
OR, you can just clone. Delete the .git folder and you're set! Just run `git init` to setup your own repo or hook it up to an existing one.

**Comment by GavPierce** [comment]
For example:
`git clone repo mySaasFolder/`
`cd mySaasFolder`
`rm -R .git` (Or Whatever your OS command is for deleting the folder)
`git init` (To create your own local repo, where you can hook it up to GitHub.com repo for example)

**Comment by Martinsos** [comment]
> I would also like to know a better way for onboarding users to use the project without just cloning the repo.
> 
> What if we add open-saas to a package directory like NPM? What if WASP could also pull it in via the CLI and it installs the boilerplate code? `wasp create saas`.

Actually, Wasp 0.12, that is coming out any second, will offer exactly what you said -> you can do `wasp new`, pick `saas`, and it will pull it for you, with no redundant files (git).

https://github.com/wasp-lang/open-saas/issues/52#issuecomment-1959344324

**Comment by vincanger** [comment]
Template Repositories seems like the correct solution 
<img width="880" alt="image" src="https://github.com/wasp-lang/open-saas/assets/70215737/c1e3d29d-5a6f-491b-9ae9-efde718bf341">
<img width="337" alt="image" src="https://github.com/wasp-lang/open-saas/assets/70215737/5f259ab9-10f7-4bfa-af7e-5bd573d029cd">

i'll update the docs now so that users don't clone the project anymore
