### ISSUE TITLE
If I sign up with Google that uses email E, and then with Github that uses same email E, Github doesn't work

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#58]
Github login just returns me back to `login/` screen, and I can't log in with Github, if I already logged in previously with Google which has same email address.

I know that accounts won't get merged, but I would expect to either have new account crated, or to get a useful error message.

It seems this is caused by the fact that `email` on `User` entity has `unique` on it.

**Comment by vincanger** [comment]
removed the unique constraint in the most recent commit
