### ISSUE TITLE
Missing OpenAI API key results in blank screen while on demo GPT app

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#60]
I start new project with open-saas, all env keys dummy/empty (as per instructions for getting started), I go to "GPT Scheduler", submit, and get blank white screen. I see errors in the console, and suggestion to add an error boundary in React -> we should probably do that? So by default errors are handled in some nicer way, not just blank screen.

**Comment by vincanger** [comment]
hm. I've provided an `.env.server.example` file and instruct users to copy this over as `.env.server` on project start. if they do that, they'll see this message @Martinsos 
![image](https://github.com/wasp-lang/open-saas/assets/70215737/e1d87c30-48a2-4b59-85af-a519626e6070)

I could add a client initiator function that throws an error if no api key is present at all (not even a dummy) that would do this:
![image](https://github.com/wasp-lang/open-saas/assets/70215737/1549e2b0-5d10-489a-b3e4-e1663bb54c8b)

wdyt?

**Comment by Martinsos** [comment]
@vincanger I followed those instructions, and I copied over that file, but I didn't get that message, I got a blank screen instead.

**Comment by vincanger** [comment]
@Martinsos odd. you'll see in the first pic above that it's showing the incomplete/dummy api key from the env vars. I've nevertheless updated it ( in commit https://github.com/wasp-lang/open-saas/commit/71238070cdf7957cceacb948d53047b41292b4a7) so that they'll see the error in the second pic above, if so.

**Comment by Martinsos** [comment]
@vincanger should we first confirm I am not having an issue anymore, before we close the issue?

We actually never reached the point where you managed to reproduce the problem I had: I claim I get blank screen, you don't know how I got there. So we can't really know if you fixed my issue at all, and if it even is an issue that we are discussing. Maybe I did something else wrong. Maybe I have this issue but you don't due to some other factors.

I would rather we investigate it a bit further, before we close this.

For example, what I can do is pull this change you did and try it again, see what happens, if I can reproduce it still.

**Comment by Martinsos** [comment]
First of all, I just realized I do always have OPENAI_API_KEY in my env, so even without it being set in .env.server, it should work. So I don't think anymore that missing env var was an issue actually when I reported this issue, it must have been something else.

Second, I just tried to reproduce it again, and I failed. I tried cloning this repo, to get th latest commit in, and couldn't reproduce it.

I also tried via `wasp new`, since that is how I got into trouble last time, and that also didn't work, couldn't reproduce.

I wonder if error was instead coming from OpenAI API due to 503 or something like that, and maybe that was crashing the app.

Anyway, it doesn't seem like missing OPENAI API key is the issue here, nor do I know how to reproduce it, so all good from my side.

**Comment by vincanger** [comment]
yes the issue was likely from OpenAI @Martinsos -- @sodic had the same problem and made me aware that it was sending back, what should have been JSON, as a weird object. As you know, the models got crappier during the "upgrade", but I resolved the issue by making the task a bit easier for it :)

**Comment by Martinsos** [comment]
> yes the issue was likely from OpenAI @Martinsos -- @sodic had the same problem and made me aware that it was sending back, what should have been JSON, as a weird object. As you know, the models got crappier during the "upgrade", but I resolved the issue by making the task a bit easier for it :)

If that is causing the blank screen, should we look into handling that in a better way then? I think we always want to avoid the blank screen, as it is quite confusing for the user.
