### ISSUE TITLE
fix conditional tailwind classes to use clsx

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#61]
currently classes use template strings for conditionals, but it's advised to use something like [clsx[(https://www.npmjs.com/package/clsx) instead

clsx + twmerge https://www.youtube.com/watch?app=desktop&v=re2JFITR7TI

**Comment by martinovicdev** [comment]
Feel free to assign me to this issue.

**Comment by martinovicdev** [comment]
No problem, I just did

**Comment by martinovicdev** [comment]
Solved through PR #71
