### ISSUE TITLE
add e2e tests 

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#64]
use playwright???

**Comment by Martinsos** [comment]
@infomiho can share his experiences with it.
Last time I was doing e2e tests, which was couple of years ago, I was making a choice between Cypress and Testcaffee. I chose Testcafe, but I think Cypress got more popular in the meantime.

**Comment by Martinsos** [comment]
Ok, playwright has ~59k stars, cypress has ~49k, testcafe has ~9k.

**Comment by infomiho** [comment]
Playwright worked for us in the main repo, let's keep using it 👍

**Comment by vincanger** [comment]
https://github.com/wasp-lang/open-saas/pull/69
