### ISSUE TITLE
configure a CI pipeline 👨‍🔧

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#65]

**Comment by GavPierce** [comment]
I'm looking into for our own project to use GitHub actions to deploy using the FlyCLI. 
open-Saas def needs to move away from direct deployment from the local development machine.

What CI/CD were you thinking of?

**Comment by infomiho** [comment]
We have this thing, we haven't tested it with the latest Wasp version https://github.com/wasp-lang/deploy-action

**Comment by vincanger** [comment]
@GavPierce i just submitted a draft PR if you wanna take a look :) https://github.com/wasp-lang/open-saas/pull/69

it's just some basic actions & e2e tests

**Comment by vincanger** [comment]
https://github.com/wasp-lang/open-saas/pull/69
