### ISSUE TITLE
Unexpected dictionary field 'userSignupFields'

### ISSUE THREAD

**Issue by peterhoang** [wasp-lang/open-saas#68]
I pulled the latest ([aa6b57](https://github.com/wasp-lang/open-saas/commit/aa6b57cafb11e069f5892a79d1d388f40d8c3525)) and when I try to ```wasp start db``` I get the following error:

```
Type error:
    Unexpected dictionary field 'userSignupFields'

    -> For dictionary field 'auth':
      -> For dictionary field 'methods':
        -> For dictionary field 'usernameAndPassword'
```

**Comment by infomiho** [comment]
Please provide your Wasp version in your report, you can find it out by running `wasp version`. 

If you have a version < 0.12, you'll need to update your Wasp by running `curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s`

**Comment by peterhoang** [comment]
> Please provide your Wasp version in your report, you can find it out by running `wasp version`.
> 
> If you have a version < 0.12, you'll need to update your Wasp by running `curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s`

Yes, thank you that was it. (I was running 0.11.8 prior to the update)
