### ISSUE TITLE
Update docs/blog theme to match design of Landing Page 

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#7]
Currently we are using the default Astro Starlight docs theme. 

Lets update it to make it look sexy and fit the style of our landing page:

Tasks:
- Check out the Starlight theming guide: https://starlight.astro.build/guides/css-and-tailwind/#theming
- Make sure it matches the color scheme on our Landing Page

**Comment by nisargpatel1504** [comment]
Hello @vincanger 

Can you please explain the features in details and would be great to work on it directly.

**Comment by og118** [comment]
Hey, in the starlight theming guide, it has steps to set up Tailwind for the project. I can contribute to set up tailwind for blogs, and match the theme of blogs with the landing page through tailwind

**Comment by vincanger** [comment]
oh nice catch @og118! I'm assigning you to this issue. Let us know if you have any Questions along the way :)

**Comment by og118** [comment]
Hi, I will raise a PR by tomorrow, Thanks!

**Comment by vincanger** [comment]
Closing this now @og118 Thanks so much 🙏 -- btw do you have a twitter account? we would love to feature your contribution!

**Comment by og118** [comment]
Sure, here you go: [Twitter](https://twitter.com/og_1181), I am not that active on Twitter, but thank you so much!

Would love to contribute here again!

**Comment by vincanger** [comment]
> Sure, here you go: [Twitter](https://twitter.com/og_1181), I am not that active on Twitter, but thank you so much!
> 

POSTED! https://x.com/WaspLang/status/1762474716487450920?s=20
