### ISSUE TITLE
Client build failing

### ISSUE THREAD

**Issue by ravikanthreddy89** [wasp-lang/open-saas#77]
NOTE: If there is any template for issues please point me and happy to format the issue. 

## Descrption
Unable to build the "client/web app". 

## Error or console log

<img width="1407" alt="Screenshot 2024-03-09 at 2 01 33 PM" src="https://github.com/wasp-lang/open-saas/assets/3085173/7abffd77-7da2-4e28-b228-1cc5671bb713">

## Environment
OS : Mac OS 13.6.4 Ventura
node : 20.10.0
npm : 10.2.3
WASP: 0.12.0

Am on latest commit from the main branch.

**Comment by ravikanthreddy89** [comment]
Switching to this tag  [wasp-v0.12-template](https://github.com/wasp-lang/open-saas/releases/tag/wasp-v0.12-template) resolved the issue. 

@vincanger  any plans to release vanila JSX template ?

**Comment by xsarahyu** [comment]
Having the same issue

**Comment by ravikanthreddy89** [comment]
@xsarahyu am using the code from this [commit](https://github.com/wasp-lang/open-saas/commit/8ec12e257c331dc0ec37f78b1f326bde0826cd8a) ?

**Comment by xsarahyu** [comment]
@ravikanthreddy89 Hey, thanks for responding! I just tried `git reset --hard 8ec12e2`, but I get `fatal: ambiguous argument '8ec12e2': unknown revision or path not in the working tree.` How did you do it?

**Comment by ravikanthreddy89** [comment]
Try creating a new branch out of the commit. 
git checkout -b <new branch name> <commit id>

**Comment by ravikanthreddy89** [comment]
@sodic  👍 thank you!

**Comment by xsarahyu** [comment]
@sodic Thanks :-)
