### ISSUE TITLE
add gist for uploading files using multer for v0.12

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/open-saas#80]
https://docs.opensaas.sh/guides/file-uploading/#using-multer-to-upload-files-to-your-server

**Comment by infomiho** [comment]
Updated the gist which shows how to upload files to 0.12: https://gist.github.com/infomiho/ec379df4e33f3ae3410a251ba3aa81af

**Comment by vincanger** [comment]
addressed in commit 76aa370b197b3206685f3fb8d749ece7af2b35c8
