### ISSUE TITLE
In docs, warn WSL users to put code on Linux file system

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/open-saas#81]
I see this being a mistake often. When using WSL on Windows, people don't put their Wasp project code on Linux filesystem but on Windows filesystem, which triggers WSL bug resulting in `wasp start` not reloading on file changes.
We have a warning about this in our docs next to installation instructions, but I think when people go through open-saas docs, they don't get an opportunity to see that part. So we should consider also putting it in open-saas, somewhere right next to instructions about WSL.

**Comment by vincanger** [comment]
addressed in commit 76aa370b197b3206685f3fb8d749ece7af2b35c8
