### ISSUE TITLE
How can I send email when user creates account with Google

### ISSUE THREAD

**Issue by nosisky** [wasp-lang/open-saas#84]
I'm trying to figure out how to send a welcome email to users who create an account with Google. I've looked through the code base and checked the `google.ts` file located at `app/src/server/auth/google.ts`. However, I couldn't find any account creation process in it. Could you please advise me on how to email users when they create an account with Google?

**Comment by vincanger** [comment]
probably the easiest way is:
- add a `welcomeEmailSent` property to your User entity and default it to `false`:
```
entity User {=psl
  id                        Int             @id @default(autoincrement())
  //...
  welcomeEmailSent Boolean @default(false)
``` 
- create a server action to send an email to the user https://wasp-lang.dev/docs/advanced/email
- check on the client in `app/src/client/App.tsx`, the App wrapper, if the user is present/logged in. If they are, check if a welcome email has been sent yet and if not, send it using the action you just created:
```ts
  useEffect(() => {
    if (!!user && !user.welcomeEmailSent) {
      sendWelcomeEmail({ userId: user.id });
    }
  }, [user]);
```

let me know if you need any other help

**Comment by nosisky** [comment]
> hey @nosisky, probably the easiest way is:
> 
> * add a `welcomeEmailSent` property to your User entity and default it to `false`:
> 
> ```
> entity User {=psl
>   id                        Int             @id @default(autoincrement())
>   //...
>   welcomeEmailSent Boolean @default(false)
> ```
> 
> * create a server action to send an email to the user https://wasp-lang.dev/docs/advanced/email
> * check on the client in `app/src/client/App.tsx`, the App wrapper, if the user is present/logged in. If they are, check if a welcome email has been sent yet and if not, send it using the action you just created:
> 
> ```ts
>   useEffect(() => {
>     if (!!user && !user.welcomeEmailSent) {
>       sendWelcomeEmail({ userId: user.id });
>     }
>   }, [user]);
> ```
> 
> let me know if you need any other help

That was very helpful! thank you @vincanger 🙏
