### ISSUE TITLE
Set custom port for frontend and backend

### ISSUE THREAD

**Issue by E5GEN2** [wasp-lang/open-saas#94]
Please add some info into the docs on how to specify a custom port for both front-end and back-end.
I get it that it has to be done in the .env files but would be awesome if it was a little bit more obvious.

**Comment by vincanger** [comment]
we defer to the Wasp Docs for stuff like this. @E5GEN2  Do you have any suggestions on where we could add a disclaimer for users of Open Saas that tells them to check out the Wasp docs if they can't find an answer to their question in the Open SaaS docs?

**Comment by vincanger** [comment]
going to close this for now. if you have any additional questions @E5GEN2 please let us know :)
