### ISSUE TITLE
Websocket keeps connecting and disconnecting

### ISSUE THREAD

**Issue by nosisky** [wasp-lang/open-saas#97]
I am having an issue where websocket keeps disconnecting and reconnecting, in my `main.wasp` file websocket autoconnect is set to true I am getting the below message:

`
{"code":1,"message":"Session ID unknown"}
`
<img width="185" alt="Screenshot 2024-04-05 at 00 16 08" src="https://github.com/wasp-lang/open-saas/assets/21035946/48fc8d0c-3792-4fb5-87d5-750eb3f9f6e0">

**Comment by vincanger** [comment]
hey @infomiho are you aware of this?

**Comment by nosisky** [comment]
I have tried using the `autoConnect: true` in main.wasp file to make websocket always connected but that didn't help, I switched to using the below useEffect to manually start socket for the component that needs it but this keeps disconnecting also.

```
 useEffect(() => {
    const handleConnect = () => {
      console.log('Connected to server');
    };

    const handleDisconnect = () => {
      console.log('Disconnected from server');
    };

    // Connect the socket if not already connected
    if (!isConnected) {
      socket.connect();
    }

    // Listen for connect and disconnect events
    socket.on('connect', handleConnect);
    socket.on('disconnect', handleDisconnect);

    // Clean up event listeners and disconnect when component unmounts
    return () => {
      socket.off('connect', handleConnect);
      socket.off('disconnect', handleDisconnect);
      socket.disconnect();
    };
  }, []);
```

it disconnects and reconnects multiple times before becoming stable.

**Comment by Martinsos** [comment]
Thanks!

Additioanl info that might help:
- rest of that component
- wasp version
- your OS
- have you maybe managed to replicate this in a very simple Wasp app? What about our https://github.com/wasp-lang/wasp/tree/main/examples/websockets-realtime-voting example, do you also get this behaviour there?

**Comment by vincanger** [comment]
Closing this for now. Let us know if you have any other questions @nosisky and we can reopen this issue. We're also available to answer questions in our Discord https://discord.gg/drqUGRrxmH
